package com.csit321.farmeddversion2.Database.Objects;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.PrimaryKey;

@Entity(tableName = "Diseases")
public class Diseases {
    @PrimaryKey(autoGenerate = true)
    private int id;
    @ColumnInfo(name = "Name of Disease")
    private String diseaseName;
    @ColumnInfo(name = "Plants Affected")
    private String plantsAffected;
    @ColumnInfo(name = "Description")
    private String description;
    @ColumnInfo(name = "mitigationsNon")
    private String mitigationsNon;
    @ColumnInfo(name = "mitigationsChemical")
    private String mitigationsChemical;
    @ColumnInfo(name = "protectiveMeasures")
    private String protectiveMeasures;
    @ColumnInfo(name = "image")
    private String image;
    @ColumnInfo(name = "link")
    private String link;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDiseaseName() {
        return diseaseName;
    }

    public void setDiseaseName(String diseaseName) {
        this.diseaseName = diseaseName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMitigationsNon() {
        return mitigationsNon;
    }

    public void setMitigationsNon(String mitigationsNon) {
        this.mitigationsNon = mitigationsNon;
    }

    public String getMitigationsChemical() {
        return mitigationsChemical;
    }

    public void setMitigationsChemical(String mitigationsChemical) {
        this.mitigationsChemical = mitigationsChemical;
    }

    public String getProtectiveMeasures() {
        return protectiveMeasures;
    }

    public void setProtectiveMeasures(String protectiveMeasures) {
        this.protectiveMeasures = protectiveMeasures;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getPlantsAffected() {
        return plantsAffected;
    }

    public void setPlantsAffected(String plantsAffected) {
        this.plantsAffected = plantsAffected;
    }

    public Diseases(String diseaseName, String plantsAffected, String description, String mitigationsNon, String mitigationsChemical, String protectiveMeasures, String image, String link) {
        this.diseaseName = diseaseName;
        this.plantsAffected = plantsAffected;
        this.description = description;
        this.mitigationsNon = mitigationsNon;
        this.mitigationsChemical = mitigationsChemical;
        this.protectiveMeasures = protectiveMeasures;
        this.image = image;
        this.link = link;
    }

    public Diseases(String id, String diseaseName, String type, String description, String plantsAffected, String mitigationsNon, String mitigationsChemical, String protectiveMeasures, String image, String link) {
        this.diseaseName = diseaseName;
        this.description = description;
        this.plantsAffected = plantsAffected;
        this.mitigationsNon = mitigationsNon;
        this.mitigationsChemical = mitigationsChemical;
        this.protectiveMeasures = protectiveMeasures;
        this.image = image;
        this.link = link;
    }



    public static Diseases[] populateData() {
        return new Diseases[] {
                new Diseases("1","Root Rot","Disease","Root Rot is a disease which affects plant roots growing in wet soil. It prevents plants from abosrbing the moisture they need to grow and gain nourishment so the plants will look as though they are suffering from a lack of water, stress or lacking minerals despite the soil being ritch or continually wet.Specifically root rot is a fungus which thrives in wet soil.","All","Once root rot is detected the crop needs to be removed to prevent spreading of the fungi through the soil. The best mitigation strategy for root rot is prevention. It spreads through wet soil so the best practices are to ensure 1. The soil is kept as dry as possible 2. Let the soil dry before irrigation 3. Ensure drainage is effective throughout farm so that water can evaporate from soil and flow away when excess is present. Raised beds where the plant root is above the soil level is effective.","Before implementing chemical products, it is best to firstly identify the fungus that is causing the problem. The fungicides should be used with caution.",null,null,"https://www.gardeningknowhow.com/plant-problems/disease/root-rot-in-garden-plants.htm"),
                new Diseases("2","Root Knot Nematode","Disease","A disease of cultivated flowers and vegetables caused by eelworm infestation, resulting in galls on the roots.","1. The solanaceae family, which includes potatoes, eggplant, capsicum, chilli and tomatoes. 2. Cucumbers, melons and pumpkins. 3.  Strawberries, peaches, bananas, grapes, passionfruit, pineapples, pawpaw.","Crop rotation is one of the oldest and most economical methods of controlling Root Knot. Practices such as removing the roots of each crop as soon as harvest is completed, followed by tilling the soil two to three times is very effective in reducing nematode levels. To kill nematodes in soil, heat small quantities of moist soil to 140°F in the oven or by solarization. Heating soil in the oven over a time period needed to bake a medium-sized potato placed in the center of the soil is sufficient to kill nematodes; however, this is only practical for small quantities of soil.","Because root-knot nematodes live in the soil, chemical control requires applications of large amounts of chemicals with specialized equipment. Fumigants (such as 1,3-dichloropropene, methyl bromide and dazomet) are commonly applied as pre-plant treatments to reduce nematode numbers, but they must thoroughly penetrate large soil volumes to be effective. Some fumigants volatilize very quickly, so treated soil must have a cover or tarp to maintain the fumigant in the soil long enough to be effective. The phasing out of methyl bromide (an efficient fumigant) has intensified the search for alternatives that can be used by farmers. In addition to broad-spectrum fumigants, nervous system toxins (including oxamyl and fenamiphos) have been shown to be extremely effective for controlling root-knot nematodes. These chemicals (carbamates and organophosphates) are extremely toxic to humans and other non-target organisms. Currently, these chemicals are the most economically feasible control method for root-knot nematodes. Because they are not toxic to plants, they are the only chemical options for established plants.",null,null,"https://www.apsnet.org/edcenter/intropp/lessons/nematodes/pages/rootknotnematode.aspx"),
                new Diseases("3","Yellow Sigakota","Disease","The earliest symptons can be found on the 3rd and 4th open leaf. Tiny, light, yellow specks (1-2mm long) appear on the upper leafe blade, parallel to the secondary veins. These specks later develop into narrow, brown or dark green spots with a spindle shape. Theses lesions expand further parallel to the veins and form oblong rusty red streaks with water-soaked centres and yellow halos (4 to 12 mm in length). The centers of the streaks gradually turn gray brown to brown, a sign of necrosis. Along the leaf margins, they coalesce to form large, black or brown necrotic leisons surrounded by patches of yellow areas. The cracking of the leaves gives them a ragged appearance.","Banana","To prevent this disease, farmers need to avoid high moisture through good drainage. Use resistant varieties (note that this can negatively impact taste). Leave sufficient space between plants to ensure good ventilation. Clear fields and surroundings of weeds. Ensure a balanced nutrition of the trees. Use fertilizers high in potassium to minimise the infestation. Apply urea as nitrogen source to compromise fungal growth on the soil. Cut off infected leaves, then burn them outside of the plantation or bury them. Biological control wth bio-fungicides based on Trichoderma atrovride have the potential to hinder the disease and are being tested for possible field applications. Bordeaux spray applied on pruning sites can hinder the progagation of the disease on these plan parts.","Fungicides containing mancozeb, calixin or chlorothalonil can be applied as foliar sprays when disease is not widespread. Rotations of systemic fungicides such as propiconazole, fenbuconazole or zeoxystrobin also work fine. The rotation is important to prevent the build up of resistance in the fungus.",null,null,"https://plantix.net/plant-disease/en/100076/yellow-sigatoka\""),
                new Diseases("4","Leaf Spot","Disease","Infected plants have brown or black water-soaked spots on the foliage, sometimes with a yellow halo, usually uniform in size. The spots enlarge and will run together under wet conditions. Under dry conditions the spots have a speckled appearance. As spots become more numerous, entire leaves may yellow, wither and drop.","All","1. Keep the soil under the tree clean and rake up fallen fruit. 2. Use a thick layer of mulch to cover the soil after you have raked and cleaned it well. Mulch will reduce weeds and prevent the disease pathogen from splashing back up onto the leaves. 3. Prune or stake plants to improve air circulation. Make sure to disinfect your pruning equipment (one part bleach to 4 parts water) after each cut. Leaf spot among vegetables is most often introduced through infected seed or transplants. 4. Spraying with a baking soda solution (a tablespoon of baking soda, 2 1/2 tablespoons of vegetable oil, a teaspoon of liquid soap, not detergent, to one gallon of water), or neem oil (do not use when pollinating insects including bees or other beneficial insects are present). Baking soda may burn some plant leaves. Spray only a few and then check for a reaction before applying applications every two weeks. 5. Apply sulfur sprays or copper-based fungicides weekly at first sign of disease to prevent its spread. These organic fungicides will not kill leaf spot, but prevent the spores from germinating.","The chemical solutions vary based on the type of crops",null,null,"https://www.planetnatural.com/pest-problem-solver/plant-disease/bacterial-leaf-spot/"),
                new Diseases("5","Powdery mildew","Disease","At first, yellow spots appear on the uppder side of leaves. At later stage of the disease, a whitish later greyish, floury covering spreads on leaves, stalks and fruits. The fungus extracts nutrients from the plant and the ash-like layer on the leaves hinders photosynthesis, resulting in stunted plant growth. As the disease progresses, infected parts shrivel, leaves fall off and plants may die.","All","Milk-waker solutions seem to work as natural fungicide. Apply this solution to the leaves every second day. This household remedy works especially well with cucurbits (cucumber, zucchini, pumpkin) and berries. The types of powdery mildew differ according to the host, and this solution may not be effective for all types. If no improvement is observed, try garlic or sodium bicarbonate solutions. Some prevention methods include: Use resistant or tolerant varieties. Plant crops with sufficient spacing to allow for good ventilation. Monitor fields regularly to assess the incidence of a disease or pest. Remove infected leaves when the first spots appear. Do not touch healthy plants after touching infected plants. A thick layer of mulch can prevent the dispersal of spores from the soil up onto the leaves. In some cases, crop rotation with non-susecptible crops works. Fertilize with a balanced nutrient supply. Avoid extreme temperature changes. Plow the soil thoroughly after harvest to dig plant residues deep into the soil. Remove plant residues after harvest.","So far, it is difficult to recommend any particular chemical treatment. Fungicides based on wettable sulphut (3g/1), hexaconazole, triflumizole, mycloobutanil (all 2m/l) seem to control the growth of the fungus in come crops.",null,null,"https://plantix.net/plant-disease/en/100002/powdery-mildew"),
                new Diseases("6","Downy Mildew","Disease","On young developing leaves, diffuse yellowish spots of different sizes appear on the upper surface. As the disease progresses, these spots enlarge and become angular, delimited by veins. Their center becomes necrotic, with different shades of brown, and they can be surrounded by a yellow halo. Usually after a series of warm humid nights, a dense, white to grayish cottony layer develops beneath these spots. The fungus extracts nutrients from the plant and causes a stunting of growth. Fruits and other plant parts can also be affected. The defoliation and the dwarfing or killing of young shoots, flowers or fruits lead to stunted growth and poor yields. In contrast to powdery mildew, the coating appear exclusively on the underside of leaves and its growth is limited by the main veins. Moreover, it cannot be removed easily.","All","In mild cases, it is often better not to do anything and wait until the weather improves. In some cases, organic pre-infection fungicides can help to avoid contamination of plants. These include copper-based fungicides, such as Bordeaux mixture.","Protectant fungicides can help to prevent the contamination of plants but they have to be sprayed properly to the underside of leaves. Fungicides of the family of the dithiocarbamates can be used. Post-infection fungicide must be applied immediately after the detection of the first symptoms. Commonly used post-infection fungicides include fosetyl-aluminum, azoxystrobin and phenylamides.",null,null,"https://plantix.net/plant-disease/en/100003/downy-mildew"),
                new Diseases("7","Magnesium Deficiency","Disease","Magnesium-deficient plants generally develop a mottled pale green or chlorotic pattern in the interveinal tissue of older leaves, often starting near the margin. In cereal, leaves with mild deficiencies develop a green linear beading that progresses to interveinal chlorosis. In severe cases, the chlorosis progresses to the middle of the leaf and the small veins also become affected. Reddish or brown spots appear on the leaf blade. Later on, the development of necrotic areas in the highly chlorotic tissue gives the leaves a rugged and deformed aspect. Finally, the yellowing engulfs the whole leaf, eventually leading to premature death and early shedding. Root growth is inhibited, resulting in poor plant vigor.","All","Apply substances that contain magnesium such as algal limestone, dolomite or limestone magnesium. Use manure, organic mulches or compost to balance the soil nutrient content. They contain organic matter and many nutrients that are released slowly into the soil.","Use soil or foliar fertilizers containing a magnesium complement. Magnesium oxide allows a slow release of the nutrient and is used in blends for an immediate supply of magnesium to crops. Magnesium sulphate releases the magnesium over a period of weeks to the soil and is ideal for a quick release requirement. An example of treatment could be the application of MgSO4 @ 10g/l of water twice at 10 days interval.",null,null,"https://plantix.net/plant-disease/en/700004/magnesium-deficiency"),
                new Diseases("11","Early blight","Disease","Symptoms of early blight occur on older foliage, stem, and fruits. Gray to brown spots appear on leaves and gradually grow in a concentric manner around a clear center - the characteristic “bullseye” formation. These lesions are surrounded by a bright yellow halo. As the disease progresses, entire leaves may turn chlorotic and shed, leading to significant defoliation. When leaves die and fall, fruits become more vulnerable to sun scald. The same type of spots with a clear center appears on stems and fruits. Rotting of fruits and sometimes dropping follows.","Capsicum & Chili, Eggplant, Tomato, Potato","Farmers may use algal limestone, a mixture of fat-free milk and water (1:1) or rock flour to treat infected plants. A solution of 3 teaspoon of bicarbonate of soda + fish emulsion in 4 liters of water also help. Application of products based on Bacillus subtilis or copper-based fungicides registered as organic also work.","There are numerous fungicides on the market for controlling early blight. Fungicides based on or combinations of azoxystrobin, pyraclostrobin, difenoconazole, boscalid, chlorothalonil, fenamidone, maneb, mancozeb, trifloxystrobin and ziram can be used. Rotation of different chemical compounds is recommended. Apply treatments in a timely manner, taking into account weather conditions. Check carefully the preharvest interval at which you can harvest safely after the application of these products.","Use certified pathogen-free seeds or transplants. Look for varieties that are resistant to the disease. Plant or transplant on raised beds to improve drainage. Orient rows in the direction H13of main winds and avoid shaded areas. Space plants to allow canopy to dry quickly after rainfall or irrigation. Lay mulch on the soil to keep plants from touching the soil. Monitor fields for signs of the disease, particularly during wet weather. Remove bottom leaves that are too close to the soil. Remove leaves displaying symptoms and destroy them. Keep plants strong and vigorous with an adequate nutrition. Use stakes to keep plants upright. Use a drip irrigation system to minimize leaf wetness. Water plants in the morning so plants dry during the day. Control susceptible weeds in and around the field. Avoid to work in fields when plants are wet. After harvest, remove plant debris and burn them (do not compost) Alternatively, plow debris deep in the soil (more than 45 cm). Plan a 2- or 3-year crop rotation with non-susceptible crops. Store tubers at cool temperatures and in well aerated sites.",null,"https://plantix.net/plant-disease/en/100321/early-blight"),
                new Diseases("12","White flies","Disease","Whiteflies are common on a variety of crops grown in open fields and greenhouses. Both adults and nymphs suck the plant sap and and excrete honeydew onto leaves, stems and fruits. Chlorotic spots and sooty molds develop on the affected tissues. During heavy infections, these spots may coalesce and spread over the whole leaf, apart from the area around the veins. The leaves may later become deformed, curl or take a cupping shape. Some whiteflies transmit viruses such as tomato yellow leaf curl virus or cassava brown streak virus.","All","Biological solutions will vary depending on the specific species of whitefly involved and the crop. Natural insecticides based on sugar-apple oil (Annona squamosa), pyrethrins, insecticidial soaps, Neem seed kernel extract (NSKE 5%), Neem oil (5ml/L water) are recommended. The parasitoid wasps Encarsia formosa, Eretmocerus eremicus, the common green lacewing Chrysoperla carnea or beetles like Delphastus spp. are also commonly used. Other natural antagonists are predatory mites, nematodes, green lacewings, ladybirds, minute pirate bugs, big-eyed bugs and damsel bugs. Pathogenic fungi include Beauveria bassiana, Isaria fumosorosea, Verticillium lecanii and Paecilomyces fumosoroseus.","Whiteflies quickly develops resistance to all pesticides, so a rotation of different products is recommendable. Apply products based on or combinations of: bifenthrin, buprofezin, fenoxycarb, deltamethrin, azadirachtin, deltamethrin, lambda-cyhalothrin, cypermethrin, pyrethroids pymetrozine or spiromesifen to control the insect. Be aware that preventive measures are often enough to reduce the population to harmless level.","Perform intercropping practices with non-susceptible plants. Use companion crops that attract or deter whiteflies (nasturtiums, zinnias, hummingbird bush, pineapple sage, bee balm). Consult with your neighbors and make sure to sow at the right time, not too early nor too late. Use denser plant space at planting. Watch for signs of whitefly on new purchases or transplants. Ensure a balanced plant fertilization. Do not use broad-spectrum insecticides that can affect beneficial insects. Remove leaves with eggs or larvae on them. At early stages of infection, place sticky traps in the fields to mass-catch whiteflies. Control weeds and alternate hosts in and around the field. Remove plant residues from the field or greenhouse after harvest. Plan a short fallow at warm temperatures. UV-absorbing greenhouse plastic films can reduce infestations.",null,"https://plantix.net/plant-disease/en/600015/whiteflies"),
                new Diseases("14","Phosphorus Deficiency","Disease","Phosphorus deficiency symptoms can appear at all stages but are more pronounced in young plants. Contrary to other nutrients, the symptoms of this deficiency are generally not very striking and can be difficult to identify. In mild cases, a possible indication for this disorder is that plants are dwarfed or stunted. However, no obvious symptoms are observed on leaves. In severe deficiencies, stem and petioles show a dark green to purple discoloration. The lower sides of older leaves also show a purple pigmentation, starting on the tips and margins and later expanding to the rest of the lamina. These leaves may become leathery and veins may form a brown netting. In some cases, phosphorus deficiency is characterized by burnt tips and the development of chlorosis as well as necrotic patches on the leaf margins. Flowers and fruits are produced, but fruit yields are low.","All","Phosphorus levels in soils can be replenished by applying farmyard manure, or other materials (organic mulch, compost and guano) or a combination thereof. The incorporation of residues to the soil after harvest can also contribute to maintaining a positive phosphorus balance in the long term and improve soil structure. The decomposition of organic matter provides a steady supply of plant-available phosphorus.","Amendments are inexpensive and varied, and they can be easily applied to alleviate deficiency problems. Phosphorus is applied to plants in the form of phosphate together with nitrogen and potassium (the N-P-K trio in fertilizer products). Soil testing is recommended to determine the ratio of each of these nutrients. It varies depending on the type of soil, the plant variety in question and the concentration of nitrogen in soil. Usually, it is recommended to apply phosphorus and potassium a few weeks before sowing or planting. Nitrogen, in turn, should be applied in split applications later during vegetative growth.","Use varieties that are efficient at mining phosphorus from the soil. Ensure a balanced and efficient fertilization of the crop. Incorporate plant residues into the soil after harvest. Use an integrated approach with mineral and organic fertilizers to keep soil nutrient balance. Lime soils if necessary to reach the appropriate soil pH.",null,"https://plantix.net/plant-disease/en/700005/phosphorus-deficiency"),
                new Diseases("15","Botrytis Blight","Disease","The profuse growth of mold on leaves, shoots, pods or fruits is the most striking symptom. Initially, sparse, tan or brown and water-soaked lesions appear on plant parts that are in contact with the soil or that have been injured. Profuse, hairy and gray to brown patches of fungal growth develop on these tissues. Later on, the mold grows on younger fruits and pods, giving them a fuzzy appearance. Alternatively, the symptoms appear during storage. In both cases, severe losses can be expected. Basal leaf and stem rots cause a total crop failure in the case of susceptible varieties of horticultural crops (damping-off). Occasionally, dieback of branches and canker formation have been observed on woody crops.","All","Biofungicides containing the competitive fungus Trichoderma harzianum are effective against gray mold on a wide range of crops. Products based on Streptomyces griseovirides are also available for use on lettuce.","Control is difficult to achieve because the fungus may colonize the host plants close to harvest time, thus preventing the application of chemicals that leave toxic residues. In case of early infections, foliar sprays with chlorothalonil can be applied to control its spread. Other fungicides based on fluazinam, and thiophante-methyl can also work. The development of resistance is common when fungicides are used intensively.","Ensure good drainage of the location and avoid inappropriate irrigation. Use healthy planting material from certified sources. Plant resistant or tolerant varieties of the crops. Plant early or early-maturing varieties. Keep a reasonable distance between the plants. Ensure an adequate row orientation and upright plants. Use mulch to impair the life cycle of the fungus and reduce the inoculum. Monitor the field and remove the decaying plant tissues. Take great care not to injure the plants when working in the field. Do not over-fertilize the crops.",null,"https://plantix.net/plant-disease/en/100081/botrytis-blight"),
                new Diseases("16","Zinc deficiencies","Disease","Zinc deficiency symptoms vary between species but several effects can be generalized. Many species show yellowing of leaves, often interveinal (main leaf veins remain green). In some species, young leaves are the most affected, but in others both old and new leaves show the symptoms. New leaves are often smaller and narrower and have wavy margins. Over time, the chlorotic spots can turn a bronze color and necrotic spots may start to develop from the margins. In some crops, zinc-deficient leaves often have shortened internodes, so leaves are clustered on the stem (rosetting). Leaf deformation and reduced growth may occur, caused by restricted development of new leaves (dwarf leaves) and reduced internode length.","All","Application of organic manure to the seedbed, or to the field a few days after transplanting reduces the odds of observing zinc deficiency.","Products containing ZnSO4 (2g/l of water) can be spread in the nursery seedbed to prevent deficiencies. Apply foliar sprays of Zinc Sulphate 0.2-0.5 % at weekly intervals or every 10 days (3 sprays) after noticing symptoms. Recommended rates of application depend on soil type and pH, and on the original concentrations of zinc in leaves. Soil applications can vary greatly depending on the parameters mentioned above but they are usually in the range of 5 to to 10 kg of zinc per hectare. Be aware that higher fertilization rates can lead to zinc toxicity. Seed coating with zinc is another way to make the micro-element available to plants. Alternatively, seeds or seedlings can be immersed in a 2-4% ZnO suspension before sowing or transplanting.","Apply organic manure before seeding or transplanting. Do not lime soils as this increases the pH and hinders zinc uptake. Choose varieties that are tolerant to zinc deficiency or better at mining zinc from the soil. Use fertilizers including zinc compounds. Use fertilizers based on urea (that generate acidity) rather than on ammonium sulfate. Make sure not to over-fertilize with phosphorus. Monitor the quality of the irrigation water regularly. Allow permanently flooded fields to drain and dry out periodically.",null,"https://plantix.net/plant-disease/en/700048/zinc-deficiency"),
                new Diseases("17","Potassium Deficiency","Disease","Symptoms are mainly visible on older leaves and start to develop on young leaves only in the case of severe deficiencies. Mild potassium deficiencies are characterized by the development of a mild chlorosis at the margins and tips of the leaves, later followed by tip burn. The leaf blade turns somewhat paler but the main veins remain dark green (interveinal chlorosis). If not amended, these chlorotic patches turn into a dry, leathery tan or dark brown scorch (necrosis) that usually progresses from the leaf edge to the midrib. However, the main veins tend to remain green. Leaves tend to curl and crinkle and often collapse prematurely. Young leaves remain small and dull, assuming a cupped appearance. Potassium-deficient plants grow stunted and are more susceptible to diseases and other stresses such as drought and frost. In some cases, fruits may be severely deformed.","All","Add organic matter in the form of ashes or plant mulch to the soil at least once a year. Wood ash also has high potassium content. Liming acidic soils can increase potassium retention in some soils by reducing leaching.","The formulation of the potassium applied can play an important role in quality and yields. The most widely used product is potassium chloride. Other mineral fertilizers include potassium nitrate, potassium sulfate, and mono-potassium phosphate. Potassium should be added as base fertilization during field preparation and a second split during flowering. A soil test can be used to determine the rate needed. Foliar sprays seem to be less effective and can burn leaves.","Highly acid or alkaline soils often lead to major and minor element deficiencies. Check the pH of the soil and lime if necessary to get the optimal range. Cultivate varieties that are more efficient in the uptake of potassium. Ensure a balanced use of fertilizers to secure a proper nutrients supply to the plant. Add organic matter to the soil in the form of manure or plant mulch. Water plants regularly and avoid flooding of fields.",null,"https://plantix.net/plant-disease/en/700002/potassium-deficiency"),
                new Diseases("18","Iron Deficiency","Disease","Symptoms of iron deficiency first appear in the youngest leaves. It is characterized by the chlorosis (yellowing) of upper leaves, with the midrib and leaf veins remaining clearly green (interveinal chlorosis). At later stages, if no measures are taken, the whole leaf turns whitish-yellow and brown necrotic spots start to appear on the leaf blade, often leading to the development of necrotic patches on the margins. Affected areas can easily be identified from a distance in the field. Leaf chlorosis and necrosis reduce chlorophyll content, inhibit the photosynthetic rate, retard growth and lower the yield potential of the plant.","All","Small holders may use a leaf fertilizer made of nettle slag and algae extract. Application of animal manures, peat and composts also add iron to the soil. Plant dandelions in proximity of your crops, since it makes iron available to nearby crops, especially trees.","Fertilize with iron-rich fertilizers. Iron is an integral part of most complete fertilizers. The application of nitric oxide (NO) alleviates leaf interveinal chlorosis and improves plant growth in plants suffering from iron deficiency in calcareous soils. This compound can also make iron more available to the plant. An example of treatment in case of acute deficiency could be: Spraying ferrous sulphate (5 g/l) + citric acid (1g/l), diluted in water, two times with weekly interval.","Choose varieties that are less-susceptible to iron deficiency. Plant dandelion nearby cultivated plants. Fertilizers that contain iron as trace element are recommended. If possible, avoid planting susceptible crops in calcareous, alkaline soils. Improve the drainage of the soils and do not over-water. Do not lime since this will increase soil pH levels.",null,"https://plantix.net/plant-disease/en/700007/iron-deficiency")

        };
    }
}
